wandb_version: 1

action_difference:
  desc: null
  value: 0.02
ang_vel_xy:
  desc: null
  value: -0.05
base_acc:
  desc: null
  value: 0.02
base_height:
  desc: null
  value: 0.008
dof_acc:
  desc: null
  value: -6.0e-07
dof_pos_limits:
  desc: null
  value: -0.3
dof_vel:
  desc: null
  value: -6.0e-05
feet_air_time:
  desc: null
  value: 1.3
foot_height:
  desc: null
  value: -0.3
foot_position_stand:
  desc: null
  value: 0.005
lin_vel_z:
  desc: null
  value: -0.8
orientation:
  desc: null
  value: -7
torques:
  desc: null
  value: 0.02
tracking_ang_vel:
  desc: null
  value: 1.0
tracking_lin_vel:
  desc: null
  value: 1.0
tracking_x_vel:
  desc: null
  value: 4
tracking_y_vel:
  desc: null
  value: 3
_wandb:
  desc: null
  value:
    python_version: 3.8.19
    cli_version: 0.16.6
    framework: huggingface
    huggingface_version: 4.11.0
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1717815725.0
    t:
      1:
      - 1
      - 11
      - 41
      - 49
      - 55
      3:
      - 16
      - 23
      4: 3.8.19
      5: 0.16.6
      6: 4.11.0
      8:
      - 5
      13: linux-x86_64
